// Dev-only generator: converts cli/assets/codeforge-icon.png into a truecolor
// half-block ANSI splash and writes cli/assets/anvil.ans.mjs. jimp is a
// devDependency used ONLY here — the runtime just prints the committed string.
//
//   node tools/gen-splash.mjs            # default 44 columns
//   node tools/gen-splash.mjs 56         # custom width in columns
//
// Rendering: each terminal cell is the '▀' (upper half block) glyph — its
// foreground color paints the TOP pixel, its background the BOTTOM pixel, so
// one row of cells encodes two rows of pixels (square aspect preserved by
// resizing the square icon to COLS×COLS px → COLS cols × COLS/2 rows).
// Near-background pixels render transparent (a space / half-block with no bg)
// so the anvil floats on the terminal background instead of a navy rectangle.

import { Jimp } from 'jimp';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(repoRoot, 'cli', 'assets', 'codeforge-icon.png');
const OUT = join(repoRoot, 'cli', 'assets', 'anvil.ans.mjs');

const COLS = Number(process.argv[2]) || 44;

const theme = {
  bg: '#0d1526',
  steel: '#7f9bb3',
  steelDim: '#3f5a63',
  molten: '#ff8a2b',
  moltenHot: '#ffd23f',
  cyan: '#39d7ff',
  text: '#dbe4ee',
};

const ESC = '';
const fg = (r, g, b) => `${ESC}[38;2;${r};${g};${b}m`;
const bg = (r, g, b) => `${ESC}[48;2;${r};${g};${b}m`;
const RESET = `${ESC}[0m`;

function dist(a, b) {
  return Math.abs(a.r - b.r) + Math.abs(a.g - b.g) + Math.abs(a.b - b.b);
}

const img = await Jimp.read(SRC);
const W = COLS;
const H = COLS; // square source → square px grid; /2 in rows via half-blocks
img.resize({ w: W, h: H });

const px = (x, y) => {
  const i = (y * img.bitmap.width + x) * 4;
  const d = img.bitmap.data;
  return { r: d[i], g: d[i + 1], b: d[i + 2], a: d[i + 3] };
};

// Background = top-left corner; anything close to it (or transparent) is "empty".
const bgc = px(0, 0);
const isEmpty = (p) => p.a < 32 || dist(p, bgc) < 44;

const lines = [];
for (let y = 0; y < H; y += 2) {
  let line = '';
  let openStyle = false;
  for (let x = 0; x < W; x++) {
    const top = px(x, y);
    const bot = y + 1 < H ? px(x, y + 1) : { ...bgc, a: 0 };
    const tE = isEmpty(top);
    const bE = isEmpty(bot);
    if (tE && bE) {
      if (openStyle) { line += RESET; openStyle = false; }
      line += ' ';
    } else if (!tE && bE) {
      line += fg(top.r, top.g, top.b) + '▀'; // ▀ top only
      openStyle = true;
    } else if (tE && !bE) {
      line += fg(bot.r, bot.g, bot.b) + '▄'; // ▄ bottom only
      openStyle = true;
    } else {
      line += fg(top.r, top.g, top.b) + bg(bot.r, bot.g, bot.b) + '▀';
      openStyle = true;
    }
  }
  if (openStyle) line += RESET;
  lines.push(line.replace(/\s+$/, '')); // trim trailing spaces
}
const art = lines.join('\n');

const file = `// GENERATED by tools/gen-splash.mjs from cli/assets/codeforge-icon.png — do not hand-edit.
// Truecolor half-block ANSI splash. Runtime only prints \`art\`; no image decoding.
export const theme = ${JSON.stringify(theme, null, 2)};

// Set CODEFORGE_NO_ART=1 to suppress the splash (e.g. non-truecolor terminals).
export const art = process.env.CODEFORGE_NO_ART ? '' : ${JSON.stringify(art)};
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}: ${lines.length} rows × ${W} cols, ${art.length} bytes`);
