#!/usr/bin/env pwsh
#
# forge-ai sync (Windows / PowerShell) — generate each engine's config + skills from the
# neutral source. No symlinks.
#
#   pwsh ./sync.ps1
#
# Single source of truth is the neutral layout at the project root:
#   CLAUDE.md                     -> instructions (also copied to AGENTS.md)
#   skills\<name>\SKILL.md        -> skills, copied into each engine's discovery dir
#   configs\claude\settings.json  -> .claude\settings.json
#   configs\codex\config.toml     -> .codex\config.toml
#   configs\opencode.json         -> opencode.json (OpenCode reads it from the root)
#
# Skill discovery differs per engine: Claude Code -> .claude\skills; Codex -> .agents\skills;
# OpenCode -> any of .opencode/.claude/.agents. So .claude\skills + .agents\skills covers all.
#
# GENERATED (do NOT hand-edit): AGENTS.md, opencode.json, .claude, .agents, .codex. Edit
# the neutral source above, then re-run this script. In an installed project these are
# committed (a clone works as-is); in the forge-ai repo itself they're gitignored dev artifacts.
#
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path

# validate required inputs BEFORE mutating anything
if (-not (Test-Path (Join-Path $Root 'skills'))) {
  Write-Host "error: no skills\ base found in $Root"; exit 2
}
$claude = Join-Path $Root 'CLAUDE.md'
if (-not (Test-Path $claude)) {
  Write-Host "error: no CLAUDE.md found in $Root"; exit 2
}

# instructions: CLAUDE.md -> AGENTS.md
Copy-Item $claude (Join-Path $Root 'AGENTS.md') -Force

# skills -> each engine's discovery dir (full mirror: replace so deletions propagate).
# .claude\skills = Claude Code (+ OpenCode); .agents\skills = Codex (+ OpenCode).
foreach ($dir in '.claude', '.agents') {
  $dirPath = Join-Path $Root $dir
  New-Item -ItemType Directory -Force -Path $dirPath | Out-Null
  $skillsPath = Join-Path $dirPath 'skills'
  if (Test-Path $skillsPath) { Remove-Item -Recurse -Force $skillsPath }
  Copy-Item -Recurse (Join-Path $Root 'skills') $skillsPath
  # ownership marker: lets the installer tell a forge-generated dir from the user's own,
  # so it never wipes a user's skills (even one coincidentally named new-feature).
  Set-Content -Path (Join-Path $skillsPath '.forge-generated') -Value 'generated by forge-ai sync — do not edit; edit ./skills instead'
}

# per-engine config, placed where each engine looks for it
New-Item -ItemType Directory -Force -Path (Join-Path $Root '.claude'), (Join-Path $Root '.codex') | Out-Null
$cClaude = Join-Path $Root 'configs\claude\settings.json'
if (Test-Path $cClaude) { Copy-Item $cClaude (Join-Path $Root '.claude\settings.json') -Force }
$cCodex = Join-Path $Root 'configs\codex\config.toml'
if (Test-Path $cCodex) { Copy-Item $cCodex (Join-Path $Root '.codex\config.toml') -Force }
$cOpen = Join-Path $Root 'configs\opencode.json'
if (Test-Path $cOpen) { Copy-Item $cOpen (Join-Path $Root 'opencode.json') -Force }

Write-Host "forge-ai sync: generated AGENTS.md, opencode.json, .claude/ (settings + skills), .agents/skills, and .codex/config.toml from the neutral source"
