#!/usr/bin/env bash
#
# forge-ai sync — generate each engine's config + skills from the neutral source.
#
#   ./sync.sh [--out <dir>]
#
# No symlinks (Windows-safe; use sync.ps1 on Windows). Inputs are read from this script's
# own project (the neutral source); outputs are written to --out (default: in place).
#
#   --out <dir>   write the generated engine artifacts into <dir> instead of alongside the
#                 source. The installer uses this to generate straight into a target project
#                 without copying the source or this script there (thin install).
#
# Neutral source layout (read from the script's dir):
#   CLAUDE.md                     → instructions (also copied to AGENTS.md)
#   skills/<name>/SKILL.md        → skills, copied into each engine's discovery dir
#   configs/claude/settings.json  → .claude/settings.json
#   configs/codex/config.toml     → .codex/config.toml
#   configs/opencode.json         → opencode.json (OpenCode reads it from the root)
#   shared/rules/*.md             → discipline (read in place by the agent; not copied here)
#
# Skill discovery paths differ per engine (verified against each CLI's docs):
#   Claude Code → .claude/skills   |   Codex → .agents/skills   |   OpenCode → any of
#   .opencode/.claude/.agents. So .claude/skills + .agents/skills covers all three.
#
# GENERATED (do NOT hand-edit — regenerated on every run): AGENTS.md, opencode.json,
# .claude/, .agents/, .codex/ (in the output dir). Edit the neutral source, then re-run.
#
set -euo pipefail
SRC_ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT_ROOT="$SRC_ROOT"

while [ $# -gt 0 ]; do
  case "$1" in
    --out)   shift; OUT_ROOT="${1:-}"; [ -n "$OUT_ROOT" ] || { echo "error: --out requires a directory" >&2; exit 2; } ;;
    --out=*) OUT_ROOT="${1#--out=}" ;;
    *)       echo "usage: $0 [--out <dir>]  (unknown arg: $1)" >&2; exit 2 ;;
  esac
  shift
done

# validate required inputs BEFORE mutating anything
[ -d "$SRC_ROOT/skills" ]    || { echo "error: no skills/ base found in $SRC_ROOT" >&2; exit 2; }
[ -f "$SRC_ROOT/CLAUDE.md" ] || { echo "error: no CLAUDE.md found in $SRC_ROOT" >&2; exit 2; }

mkdir -p "$OUT_ROOT"
OUT_ROOT="$(cd "$OUT_ROOT" && pwd)"

# instructions: CLAUDE.md -> AGENTS.md (Codex + OpenCode read AGENTS.md)
cp "$SRC_ROOT/CLAUDE.md" "$OUT_ROOT/AGENTS.md"

# skills -> each engine's discovery dir (full mirror: replace so deletions propagate).
# .claude/skills = Claude Code (+ OpenCode); .agents/skills = Codex (+ OpenCode).
for dir in .claude .agents; do
  mkdir -p "$OUT_ROOT/$dir"
  rm -rf "$OUT_ROOT/$dir/skills"
  cp -R "$SRC_ROOT/skills" "$OUT_ROOT/$dir/skills"
  # ownership marker: lets the installer tell a forge-generated dir from the user's own,
  # so it never wipes a user's skills (even one coincidentally named new-feature).
  printf 'generated by forge-ai sync — do not edit; edit the forge-ai source instead\n' > "$OUT_ROOT/$dir/skills/.forge-generated"
done

# per-engine config, placed where each engine looks for it
mkdir -p "$OUT_ROOT/.claude" "$OUT_ROOT/.codex"
[ -f "$SRC_ROOT/configs/claude/settings.json" ] && cp "$SRC_ROOT/configs/claude/settings.json" "$OUT_ROOT/.claude/settings.json"
[ -f "$SRC_ROOT/configs/codex/config.toml" ]    && cp "$SRC_ROOT/configs/codex/config.toml"    "$OUT_ROOT/.codex/config.toml"
[ -f "$SRC_ROOT/configs/opencode.json" ]        && cp "$SRC_ROOT/configs/opencode.json"        "$OUT_ROOT/opencode.json"

echo "forge-ai sync: generated AGENTS.md, opencode.json, .claude/ (settings + skills), .agents/skills, and .codex/config.toml into $OUT_ROOT"
