#!/usr/bin/env pwsh
#
# codeforge sync (Windows / PowerShell) — generate each engine's config + skills from the
# neutral source. No symlinks.
#
#   pwsh ./sync.ps1 [-Out <dir>]
#
# Inputs are read from this script's own project (the neutral source); outputs are written
# to -Out (default: in place). The installer uses -Out to generate straight into a target
# project without copying the source or this script there (thin install).
#
# Neutral source layout (read from the script's dir):
#   CLAUDE.md                     -> instructions (also copied to AGENTS.md)
#   skills\<name>\SKILL.md        -> skills, copied into each engine's discovery dir
#   configs\claude\settings.json  -> .claude\settings.json
#   configs\codex\config.toml     -> .codex\config.toml
#   configs\opencode.json         -> opencode.json (OpenCode reads it from the root)
#
# Skill discovery differs per engine: Claude Code -> .claude\skills; Codex -> .agents\skills;
# OpenCode -> any of .opencode/.claude/.agents. So .claude\skills + .agents\skills covers all.
#
# GENERATED (do NOT hand-edit): AGENTS.md, opencode.json, .claude, .agents, .codex (in the
# output dir). Edit the neutral source above, then re-run this script.
#
param(
  [string]$Out
)
$ErrorActionPreference = 'Stop'
$SrcRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$OutRoot = if ($Out) { $Out } else { $SrcRoot }

# validate required inputs BEFORE mutating anything
if (-not (Test-Path (Join-Path $SrcRoot 'skills'))) {
  Write-Host "error: no skills\ base found in $SrcRoot"; exit 2
}
$claude = Join-Path $SrcRoot 'CLAUDE.md'
if (-not (Test-Path $claude)) {
  Write-Host "error: no CLAUDE.md found in $SrcRoot"; exit 2
}

New-Item -ItemType Directory -Force -Path $OutRoot | Out-Null
$OutRoot = (Resolve-Path $OutRoot).Path

# instructions: CLAUDE.md -> AGENTS.md
Copy-Item $claude (Join-Path $OutRoot 'AGENTS.md') -Force

# skills -> each engine's discovery dir (full mirror: replace so deletions propagate).
# .claude\skills = Claude Code (+ OpenCode); .agents\skills = Codex (+ OpenCode).
foreach ($dir in '.claude', '.agents') {
  $dirPath = Join-Path $OutRoot $dir
  New-Item -ItemType Directory -Force -Path $dirPath | Out-Null
  $skillsPath = Join-Path $dirPath 'skills'
  if (Test-Path $skillsPath) { Remove-Item -Recurse -Force $skillsPath }
  Copy-Item -Recurse (Join-Path $SrcRoot 'skills') $skillsPath
  # ownership marker: lets the installer tell a forge-generated dir from the user's own,
  # so it never wipes a user's skills (even one coincidentally named new-feature).
  Set-Content -Path (Join-Path $skillsPath '.forge-generated') -Value 'generated by codeforge sync — do not edit; edit the codeforge source instead'
}

# per-engine config, placed where each engine looks for it
New-Item -ItemType Directory -Force -Path (Join-Path $OutRoot '.claude'), (Join-Path $OutRoot '.codex') | Out-Null
$cClaude = Join-Path $SrcRoot 'configs\claude\settings.json'
if (Test-Path $cClaude) { Copy-Item $cClaude (Join-Path $OutRoot '.claude\settings.json') -Force }
$cCodex = Join-Path $SrcRoot 'configs\codex\config.toml'
if (Test-Path $cCodex) { Copy-Item $cCodex (Join-Path $OutRoot '.codex\config.toml') -Force }
$cOpen = Join-Path $SrcRoot 'configs\opencode.json'
if (Test-Path $cOpen) { Copy-Item $cOpen (Join-Path $OutRoot 'opencode.json') -Force }

Write-Host "codeforge sync: generated AGENTS.md, opencode.json, .claude/ (settings + skills), .agents/skills, and .codex/config.toml into $OutRoot"
